### PR TITLE
Update s3 archiver

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
S3 archiver has hard-coded StorageClass values, needs some polishing

## Approach
* Update to Python 3.9
* Parameterize the StorageClass values
* Change `REDUCED_REDUNDANCY` default to `INTELLIGENT_TIERING`
* Stub out expected envvars in Dockerfile
* Fix bad copy-paste in the Dockerfile
* Update documentation (root README and wiki page still need to be updated to reflect new parameters)

## How to Test
TBD

### CODE REVIEW

**Comment by robkooper** [comment]
I'm fine with updating the documentation on the WIKI by just having a big bold text that says the most up to date documentation is found on github and a pointer to the README here.

**Review by lmarini — COMMENTED** [review]
When I try the disk archiver I am getting the following error:

```2021-03-29 17:20:48,059 [Thread-16      ] INFO    : pyclowder.connectors - [60620c6019ec868dbdc91fd3] : StatusMessage.start: Started processing.
2021-03-29 17:20:48,059 [Thread-16      ] DEBUG   : pyclowder.extractors - default check message : {'notifies': ['lmarini@illinois.edu'], 'source': {'id': {'resourceType': "'file", 'id': '60620c6019ec868dbdc91fd3'}, 'mimeType': 'image/jpeg', 'extra': {'filename': '9xLwvaT.jpg'}}, 'jobid': '60620c7019ec868dbdc91fd8', 'msgid': '60620c7019ec868dbdc91fd9', 'flags': '', 'intermediateId': '60620c6019ec868dbdc91fd3', 'host': 'http://192.168.29.207:9000/clowder', 'datasetId': '605cbfdb9c507f6cf06ba934', 'id': '60620c6019ec868dbdc91fd3', 'fileSize': '190497', 'filename': '9xLwvaT.jpg', 'target': '{}', 'secretKey': 'xxxxxxx', 'activity': 'submitted', 'routing_key': 'extractors.ncsa.archival.disk', 'parameters': {'operation': 'archive'}, 'action': 'manual-submission'}
2021-03-29 17:20:48,076 [Thread-16      ] INFO    : pyclowder.connectors - [60620c6019ec868dbdc91fd3] : StatusMessage.processing: Downloading file.
2021-03-29 17:20:48,123 [Thread-16      ] INFO    : DiskArchiver - Operation == archive
2021-03-29 17:20:48,123 [Thread-16      ] ERROR   : DiskArchiver - Input path (/tmp/tmphyamjl89.jpg) is not in the Clowder data directory (/Users/lmarini/data/clowder/uploads). Aborting.
2021-03-29 17:20:48,124 [Thread-16      ] INFO    : pyclowder.connectors - [60620c6019ec868dbdc91fd3] : StatusMessage.done: Done processing.
```
Looks like it is using the tmp file name?

I am starting it like this 

```docker run --net=host -it --rm -e ARCHIVE_SOURCE_DIRECTORY=/Users/lmarini/data/clowder/uploads -e ARCHIVE_TARGET_DIRECTORY=/Users/lmarini/data/clowder/archive clowder/extractors-archival-disk```

**Comment by bodom0015** [comment]
There is a note about this in the documentation and a FIXME in the source:

> NOTE: MOUNTED_PATHS configuration is currently required without modifications to the Python code, since we require direct write access to the data directory. This prevents us from needing to download the file to archive or unarchive it. See [Mounted Paths](https://opensource.ncsa.illinois.edu/confluence/display/CATS/Advanced+Configuration+Options#AdvancedConfigurationOptions-MountedPaths) for notes about configuring the `MOUNTED_PATHS` environment variable.

```
    # FIXME: Specifying "bypass" here does not actually download the file
    # The next time the auto-archive loop runs, this file will be archived again
    #def check_message(self, connector, host, secret_key, resource, parameters):
    #    return CheckMessage.bypass
```

Unfortunately, this disk archiver assumes it has disk access to Clowder's file store. Because of how CheckMessage works, we cannot use `CheckMessage.bypass`, as that appears to also skip `process_message`. So we need to use `MOUNTED_PATHS` in conjunction with `-v ` to tell the archiver where the files will live:
 ```bash
docker run --net=host -itd -e MOUNTED_PATHS='{ "/Users/lambert8/clowder/data":"/home/clowder/clowder/data" }' -v /Users/lambert8/clowder/data/:/home/clowder/clowder/data -e ARCHIVE_SOURCE_DIRECTORY="/home/clowder/clowder/data/uploads/" -e ARCHIVE_TARGET_DIRECTORY="/home/clowder/clowder/data/archive/" clowder/extractors-archival-disk
```

Note that `MOUNTED_PATHS` matches the mapping provided by `-v`:
 `/Users/lambert8/clowder/data` -> `/home/clowder/clowder/data`

This allows the archiver to use the files-at-rest in Clowder without needing to re-download them.

**Comment by lmarini** [comment]
> There is a note about this in the documentation and a FIXME in the source:
> 
> > NOTE: MOUNTED_PATHS configuration is currently required without modifications to the Python code, since we require direct write access to the data directory. This prevents us from needing to download the file to archive or unarchive it. See [Mounted Paths](https://opensource.ncsa.illinois.edu/confluence/display/CATS/Advanced+Configuration+Options#AdvancedConfigurationOptions-MountedPaths) for notes about configuring the `MOUNTED_PATHS` environment variable.
> 
> ```
>     # FIXME: Specifying "bypass" here does not actually download the file
>     # The next time the auto-archive loop runs, this file will be archived again
>     #def check_message(self, connector, host, secret_key, resource, parameters):
>     #    return CheckMessage.bypass
> ```
> 
> Unfortunately, this disk archiver assumes it has disk access to Clowder's file store. Because of how CheckMessage works, we cannot use `CheckMessage.bypass`, as that appears to also skip `process_message`. So we need to use `MOUNTED_PATHS` in conjunction with `-v ` to tell the archiver where the files will live:
> 
> ```shell
> docker run --net=host -itd -e MOUNTED_PATHS='{ "/Users/lambert8/clowder/data":"/home/clowder/clowder/data" }' -v /Users/lambert8/clowder/data/:/home/clowder/clowder/data -e ARCHIVE_SOURCE_DIRECTORY="/home/clowder/clowder/data/uploads/" -e ARCHIVE_TARGET_DIRECTORY="/home/clowder/clowder/data/archive/" clowder/extractors-archival-disk
> ```
> 
> Note that `MOUNTED_PATHS` matches the mapping provided by `-v`:
> `/Users/lambert8/clowder/data` -> `/home/clowder/clowder/data`
> 
> This allows the archiver to use the files-at-rest in Clowder without needing to re-download them.

Got it, thank you @bodom0015

**Review by lmarini — APPROVED** [review]

**Pull request merged**
